//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditRejection
    {
        public long Id { get; set; }
        public long ReceiptId { get; set; }
        public long ReasonId { get; set; }
        public bool Active { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        public virtual CreditReason Reason { get; set; }
        public virtual CreditReceipt Receipt { get; set; }
    }
}
