//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentation
    {
        public long Id { get; set; }
        public long Id_Unit { get; set; }
        public long Id_InstrumentationType { get; set; }
        public string Indice { get; set; }
        public string Descripcion { get; set; }
        public bool Preset { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        public virtual InstrumentationType InstrumentationType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
