//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentation
    {
        public long Id { get; set; }
        public long Id_Unit { get; set; }
        public long Id_InstrumentationType { get; set; }
        public string Indice { get; set; }
        public string Descripcion { get; set; }
        public bool Preset { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        public virtual InstrumentationType InstrumentationType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
