//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFile
    {
        public long Id { get; set; }
        public Nullable<long> Id_Project { get; set; }
        public Nullable<long> Id_FileType { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Ruta { get; set; }
        public bool Proyecto { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual Project Project { get; set; }
    }
}
