//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.Attempts = new HashSet<Attempt>();
            this.Rejections = new HashSet<Rejection>();
        }
    
        public long Id { get; set; }
        public long PersonId { get; set; }
        public long PaymentId { get; set; }
        public long MethodId { get; set; }
        public long PhaseId { get; set; }
        public string Voucher { get; set; }
        public string Image { get; set; }
        public string Invoice { get; set; }
        public Nullable<long> InvoicedBy { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attempt> Attempts { get; set; }
        public virtual Method Method { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rejection> Rejections { get; set; }
    }
}
