//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejection
    {
        public long Id { get; set; }
        public long ReceiptId { get; set; }
        public long ReasonId { get; set; }
        public bool Active { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    
        public virtual Reason Reason { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
