//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scope
    {
        public long Id { get; set; }
        public long Id_Unit { get; set; }
        public string Indicador { get; set; }
        public int Valor { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
