//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scope
    {
        public long Id { get; set; }
        public long Id_Unit { get; set; }
        public string Indicador { get; set; }
        public int Valor { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
