//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPRET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEPRETEntities : DbContext
    {
        public SEPRETEntities()
            : base("name=SEPRETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attempt> Attempts { get; set; }
        public virtual DbSet<Method> Methods { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Rejection> Rejections { get; set; }
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonPermission> PersonPermissions { get; set; }
        public virtual DbSet<Adviser> Advisers { get; set; }
        public virtual DbSet<AdviserType> AdviserTypes { get; set; }
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<Ambit> Ambits { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CommentType> CommentTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Dictum> Dicta { get; set; }
        public virtual DbSet<FileDictum> FileDictums { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectCareer> ProjectCareers { get; set; }
        public virtual DbSet<ProjectCompany> ProjectCompanies { get; set; }
        public virtual DbSet<ProjectFile> ProjectFiles { get; set; }
        public virtual DbSet<ProjectPerson> ProjectPersons { get; set; }
        public virtual DbSet<ProjectPhase> ProjectPhases { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<SpecificObjective> SpecificObjectives { get; set; }
        public virtual DbSet<Instrumentation> Instrumentations { get; set; }
        public virtual DbSet<InstrumentationType> InstrumentationTypes { get; set; }
        public virtual DbSet<PersonSubject> PersonSubjects { get; set; }
        public virtual DbSet<Scope> Scopes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
